# Generated by Django 5.2.1 on 2025-06-09 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
